[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {
         \ 'colorscheme': 'landscape',
         \ 'active': {
         \   'left': [ [ 'mode', 'paste' ],
         \             [ 'fugitive', 'filename' ] ],
         \   'right': [ [ 'syntastic', 'lineinfo' ],
         \              ['percent'],
         \              [ 'fileformat', 'fileencoding', 'filetype' ] ]
         \ },
         \ 'component_function': {
         \   'fugitive': 'LightLineFugitive',
         \   'readonly': 'LightLineReadonly',
         \   'modified': 'LightLineModified',
         \   'fileformat': 'LightLineFileformat',
         \   'filetype': 'LightLineFiletype',
         \   'fileencoding': 'LightLineFileencoding',
         \   'mode': 'LightLineMode',
         \   'filename': 'LightLineFilename'
         \ },
         \ 'component_expand': {
         \   'syntastic': 'SyntasticStatuslineFlag',
         \ },
         \ 'component_type': {
         \   'syntastic': 'error',
         \ },
         \ 'separator': { 'left': "\ue0b0", 'right': "\ue0b2" },
         \ 'subseparator': { 'left': "\ue0b1", 'right': "\ue0b3" }
         \ }

    function! LightLineModified()
     if &filetype == "help"
       return ""
     elseif &modified
       return "+"
     elseif &modifiable
       return ""
     else
       return ""
     endif
    endfunction

    function! LightLineReadonly()
     if &filetype == "help"
       return ""
     elseif &readonly
       return "⭤"
     else
       return ""
     endif
    endfunction

    function! LightLineFilename()
     return ('' != LightLineReadonly() ? LightLineReadonly() . ' ' : '') .
          \ ('' != expand('%:t') ? expand('%:t') : '[No Name]') .
          \ ('' != LightLineModified() ? ' ' . LightLineModified() : '')
    endfunction

    function! LightLineFugitive()
     if exists("*fugitive#head")
       let _ = fugitive#head()
       return strlen(_) ? "\ue0a0 "._ : ''
     endif
     return ''
    endfunction

    function! LightLineFileformat()
     return winwidth(0) > 70 ? &fileformat : ''
    endfunction

    function! LightLineFiletype()
     return winwidth(0) > 70 ? (strlen(&filetype) ? &filetype : 'no ft') : ''
    endfunction

    function! LightLineFileencoding()
     return winwidth(0) > 70 ? (strlen(&fenc) ? &fenc : &enc) : ''
    endfunction

    function! LightLineMode()
     let fname = expand('%:t')
     return  fname == '__Gundo__' ? 'Gundo' :
           \ fname == '__Gundo_Preview__' ? 'Gundo Preview' :
           \ &ft == 'unite' ? 'Unite' :
           \ &ft == 'vimshell' ? 'VimShell' :
           \ winwidth(0) > 60 ? lightline#mode() : ''
    endfunction

    let g:tagbar_status_func = 'TagbarStatusFunc'

    function! TagbarStatusFunc(current, sort, fname, ...) abort
       let g:lightline.fname = a:fname
     return lightline#statusline(0)
    endfunction

    augroup AutoSyntastic
     autocmd!
     autocmd BufWritePost *.py,*.js,*.java,*.c,*.cpp call s:syntastic()
    augroup END
    function! s:syntastic()
     SyntasticCheck
     call lightline#update()
    endfunction

    let g:unite_force_overwrite_statusline = 0
    let g:vimshell_force_overwrite_statusline = 0
'''

[[plugins]]
repo = 'vim-scripts/changed'

[[plugins]]
repo = 'bkad/CamelCaseMotion'
hook_add = '''
    map <silent> w <Plug>CamelCaseMotion_w
    map <silent> b <Plug>CamelCaseMotion_b
    map <silent> e <Plug>CamelCaseMotion_e
    map <silent> ge <Plug>CamelCaseMotion_ge
    sunmap w
    sunmap b
    sunmap e
    sunmap ge
'''

[[plugins]]
repo = 'sjl/gundo.vim'
hook_add = '''
    let g:gundo_right = 1
    nnoremap U :<C-u>GundoToggle<CR><C-w>p
    nnoremap <silent> <F5> :<C-u>silent! GundoRenderGraph<CR><C-w>p
'''

[[plugins]]
repo = 'Lokaltog/vim-easymotion'
hook_add = '''
    let g:EasyMotion_use_migemo = 1
    " cmigemoのインストールが必要
    nmap s <Plug>(easymotion-s)
    vmap s <Plug>(easymotion-s)
    omap z <Plug>(easymotion-s)
'''

[[plugins]]
repo = 'rhysd/clever-f.vim'
hook_add = '''
    " 大文字を入力した時のみ大文字小文字を区別
    let g:clever_f_smart_case = 1
    " ローマ字入力で日本語も検索
    let g:clever_f_use_migemo = 1
'''
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'cohama/agit.vim'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''
